---
- name: Confirm Prereqs
  ansible.builtin.apt:
    name: ["ca-certificates", "curl", "gnupg", "lsb-release"]
    update_cache: true
    
- name: Add Docker GPG Key
  ansible.builtin.shell:
    cmd: wget -qO - https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Docker Repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
    update_cache: false

- name: Install Docker components
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Add Seclab to Docker
  ansible.builtin.user:
    groups: docker
    append: true
    name: kasm
